baseURL: ''
languageCode: en-us
title: Sadatuzzaman Saagoto
theme: PaperMod


menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

    - indentifer: website
      name: My Website
      url: https://sadatuzzaman.github.io
      weight: 10
